# Generated by Django 5.2.7 on 2026-02-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0004_tbl_vendor_gstin'),
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_type', models.CharField(choices=[('daily', 'Daily Rent'), ('monthly', 'Monthly Rent')], max_length=10)),
                ('rental_duration', models.PositiveIntegerField(help_text='Number of days or months')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rent_price', models.DecimalField(decimal_places=2, help_text='Price per day or per month', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='Total rent + security deposit', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='GuestApp.tbl_customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='VendorApp.tbl_product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
                'db_table': 'tbl_cart',
                'unique_together': {('customer', 'product', 'rent_type')},
            },
        ),
    ]
