# Generated by Django 5.2.7 on 2026-02-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0002_tbl_delivery_address'),
        ('GuestApp', '0004_tbl_vendor_gstin'),
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Vendor Confirmed'), ('paid', 'Payment Completed'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='GuestApp.tbl_customer')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomerApp.tbl_delivery_address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'tbl_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='tbl_order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_type', models.CharField(max_length=10)),
                ('rental_duration', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CustomerApp.tbl_order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='VendorApp.tbl_product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'tbl_order_item',
            },
        ),
    ]
