# Generated by Django 5.2.7 on 2026-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0003_tbl_order_tbl_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_order_item',
            name='rent_type',
            field=models.CharField(choices=[('daily', 'Daily Rent'), ('monthly', 'Monthly Rent')], max_length=10),
        ),
    ]
