# Generated by Django 5.2.7 on 2026-02-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0008_add_returns_system'),
        ('GuestApp', '0004_tbl_vendor_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_return_request',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='GuestApp.tbl_customer'),
        ),
    ]
