# Generated by Django 5.2.7 on 2026-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0009_alter_tbl_return_request_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order_item',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_order_item',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
