# Generated by Django 5.2.7 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0010_tbl_order_item_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
