# Generated by Django 5.2.7 on 2026-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0011_tbl_cart_rental_end_date_tbl_cart_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Vendor Confirmed'), ('paid', 'Payment Completed'), ('delivered', 'Delivered'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
