# Generated by Django 5.2.7 on 2026-01-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0005_tbl_subcategory'),
        ('GuestApp', '0004_tbl_vendor_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('product_image', models.ImageField(upload_to='product_images/main/')),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AdminApp.tbl_categorys')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AdminApp.tbl_subcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='GuestApp.tbl_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_furniture_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('thickness', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('extra_features', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_details', to='VendorApp.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_appliance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=50)),
                ('voltage', models.CharField(max_length=50)),
                ('warranty_period', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_details', to='VendorApp.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='VendorApp.tbl_product')),
            ],
        ),
    ]
