# Generated by Django 5.2.7 on 2026-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
