# Generated by Django 5.2.7 on 2025-12-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_district')),
            ],
        ),
    ]
