# Generated by Django 5.2.7 on 2026-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_categorys',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category_image', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
