# Generated by Django 5.2.7 on 2026-01-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_tbl_categorys_category_name'),
        ('GuestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_login',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='customer_id_proofs/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_district')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='GuestApp.tbl_login')),
            ],
        ),
    ]
