# Generated by Django 5.2.7 on 2026-01-27 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_tbl_subcategory'),
        ('GuestApp', '0002_alter_tbl_login_username_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('aadhar_proof', models.FileField(upload_to='vendor/aadhar/')),
                ('shop_license', models.FileField(upload_to='vendor/shop_license/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_district')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='GuestApp.tbl_login')),
            ],
        ),
    ]
