# Generated by Django 5.2.7 on 2026-01-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0003_tbl_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
